ServerEvents.recipes(e => {
    // 钻石粉碎
    e.recipes.create.crushing(
        [
            "mekanism:dust_diamond",
            Item.of("mekanism:dust_diamond").withChance(0.25)
        ],
        [
            "minecraft:diamond"
        ])
            .id("create:crushing/dust_diamond")
    e.recipes.create.crushing(        
        [
            "mekanism:dust_gold",
            Item.of("mekanism:dust_gold").withChance(0.25)
        ],
        [
            "minecraft:gold_ingot"
        ])
            .id("create:crushing/dust_gold")
    e.recipes.create.crushing(
        [
            "mekanism:dust_bronze",
            Item.of("mekanism:dust_bronze").withChance(0.25)
        ],
        [
            "alloyed:bronze_ingot"
        ])
    e.recipes.create.crushing(
        [
            "mekanism:dust_lapis_lazuli",
            Item.of("mekanism:dust_lapis_lazuli").withChance(0.25)
        ],
        [
            "minecraft:lapis_lazuli"
        ])
    e.recipes.create.crushing(
        [
            "mekanism:dust_quartz",
            Item.of("mekanism:dust_quartz").withChance(0.25)
        ],
        [
            "minecraft:quartz"
        ])
    e.recipes.create.crushing(
        [
            "mekanism:dust_steel",
            Item.of("mekanism:dust_steel").withChance(0.25)
        ],
        [
            "createindustry:steel_ingot"
        ])
    e.recipes.create.crushing(
        [
            "mekanism:dust_emerald",
            Item.of("mekanism:dust_emerald").withChance(0.25)
        ],
        [
            "minecraft:emerald"
        ])
    e.recipes.create.crushing(
        [
            "mekanism:dust_netherite",
            Item.of("mekanism:dust_netherite").withChance(0.25)
        ],
        [
            "minecraft:netherite_ingot"
        ])
    e.recipes.create.crushing(
        [
            "mekanism:dust_fluorite",
            Item.of("mekanism:dust_fluorite").withChance(0.25)
        ],
        [
            "mekanism:fluorite_gem"
        ])
    e.recipes.create.crushing(
        [
            "mekanism:dust_iron",
            Item.of("mekanism:dust_iron").withChance(0.25)
        ],
        [
            "minecraft:iron_ingot"
        ])
    e.recipes.create.crushing(
        [
            "mekanism:dust_osmium",
            Item.of("mekanism:dust_osmium").withChance(0.25)
        ],
        [
            "mekanism:ingot_osmium"
        ])
    e.recipes.create.crushing(
        [
            "mekanism:dust_copper",
            Item.of("mekanism:dust_copper").withChance(0.25)
        ],
        [
            "minecraft:copper_ingot"
        ])
    e.recipes.create.crushing(
        [
            "mekanism:dust_tin",
            Item.of("mekanism:dust_tin").withChance(0.25)
        ],
        [
            "mekanism:ingot_tin"
        ])
    e.recipes.create.crushing(
        [
            "mekanism:dust_lead",
            Item.of("mekanism:dust_lead").withChance(0.25)
        ],
        [
            "mekanism:ingot_lead"
        ])
    e.recipes.create.crushing(
        [
            "mekanism:dust_uranium",
            Item.of("mekanism:dust_uranium",).withChance(0.25)
        ],
        [
            "mekanism:ingot_uranium"
        ])
    // 焦煤粉 
    e.recipes.create.milling(
        [
            "createindustry:coal_coke_dust",
        ],
        [
            "createindustry:coal_coke"
        ])
            .id("create:crushing/coal_coke_dust")
    e.recipes.create.milling(
        [
            "mekanism:dust_coal"
        ],
        [
            "minecraft:coal"
        ]
    )
    e.recipes.create.milling(
        [
            "mekanism:dust_charcoal"
        ],
        [
            "minecraft:charcoal"
        ]
    )
})
