ServerEvents.recipes(e=>{
    e.recipes.create.mechanical_crafting('kubejs:final_eye',[
        'ABCDA',
        'EFFFG',
        'HFIFJ',
        'KFFFL',
        'AMNOA'
    ],{
        A:'minecraft:ender_eye',
        B:'endrem:lost_eye',
        C:'endrem:rogue_eye',
        D:'endrem:undead_eye',
        E:'endrem:witch_eye',
        F:'ends_delight:dragon_tooth',
        G:'endrem:magical_eye',
        H:'endrem:wither_eye',
        I:'minecraft:end_crystal',
        J:'endrem:nether_eye',
        K:'endrem:cold_eye',
        L:'endrem:exotic_eye',
        M:'endrem:cursed_eye',
        N:'endrem:evil_eye',
        O:'endrem:black_eye'
    })
})