JEIEvents.hideItems(e=>{
    e.hide('create_sa:drone_controller')
    e.hide('create_sa:brass_drone_item')
    e.hide('create_sa:copper_magnet')
    e.hide('create_sa:fan_component')
    e.hide('create_sa:vault_component')
    e.hide('create_sa:block_picker')
    e.hide('create_sa:brass_cube')
    e.hide('ad_astra:compressor')
    e.hide('ad_astra:nasa_workbench')
    e.hide('ad_astra:water_pump')
    e.hide('ad_astra:wrench')
    e.hide('ad_astra:hammer')
    e.hide('ad_astra:steel_cable')
    e.hide('ad_astra:desh_cable')
    e.hide('ad_astra:desh_fluid_pipe')
    e.hide('ad_astra:ostrum_fluid_pipe')
    e.hide('ad_astra:cable_duct')
    e.hide('ad_astra:fluid_pipe_duct')
    e.hide('ad_astra:coal_generator')
    e.hide('ad_astra:iron_plate')
    e.hide('ad_astra:steel_plate')
    e.hide('ad_astra:iron_rod')
    e.hide('ad_astra:steel_ingot')
    e.hide('alloyedguns:musket')
    e.hide('alloyedguns:flintlock')
    e.hide('cgm:workbench')
    e.hide('create_enchantment_industry:experience_rotor')
    e.hide('cgm:crude_shot')
    e.hide('alloyedguns:complex_bullet_casing')
    e.hide('alloyedguns:complex_bullet')
    e.hide('alloyedguns:small_iron_pipe')
    e.hide('vinery:cherry_boat')
    e.hide('beachparty:palm_boat')
    e.hide('beachparty:palm_chest_boat')
    e.hide('vinery:cherry_chest_boat')
    e.hide([
        'createaddition:tesla_coil',
        'createaddition:electrum_amulet',
        'createaddition:copper_wire',
        'createaddition:iron_wire',
        'createaddition:spool',
        'createaddition:electrum_rod',
        'createaddition:gold_rod',
        'createaddition:brass_rod',
        'createaddition:festive_spool',
        'createaddition:gold_spool',
        'createaddition:electrum_spool',
        'createaddition:electric_motor',
        'createaddition:alternator',
        'createaddition:connector',
        'createaddition:small_light_connector',
        'createaddition:large_connector',
        'createaddition:redstone_relay',
        'create_sa:block_picker',
        'refinedstorage:wrench',
        'refinedstorage:raw_basic_processor',
        'refinedstorage:raw_improved_processor',
        'refinedstorage:raw_advanced_processor'
    ])
})
