#Enable the the spawning of enchanted mobs. [true / false]
"Enchanted Mob can Spawn Natural" = true
#Disables specific mob from receiveing enchantments on spawn. Use the full name, eg: minecraft:ender_dragon.
enchantOnSpawnExclusionMobs = ["minecraft:wither", "minecraft:ender_dragon"]
#Allow the specific mob from alway receiveing enchantments on spawn. Use the full name, eg: minecraft:zombie.
alwayEnchantableMobs = []
#Allow the specific mob from alway receiveing enchantments as Ancient Mob on spawn(This feature may break for balance so be careful). Use the full name, eg: minecraft:zombie.
alwayEnchantableAncientMobs = []
#Disables the specific mob enchant. Use the full name(This config only disabled mob enchant when mob spawn. not mean delete complete, eg: enchantwithmob:thorn.
disableMobEnchants = []
#Allow the poison cloud for projectile. Use the full name(eg: minecraft:arrow.
allowPoisonCloudProjectiles = ["minecraft:arrow", "minecraft:snowball", "earthmobsmod:melon_seeds", "earthmobsmod:zombie_flesh", "conjurer_illager:throwing_card", "conjurer_illager:bouncy_ball", "tofucraft:fukumame", "tofucraft:nether_fukumame", "tofucraft:soul_fukumame"]
#Allow the multi shot for projectile. Use the full name(eg: minecraft:arrow.
allowMultiShotProjectiles = ["minecraft:arrow", "minecraft:snowball", "earthmobsmod:melon_seeds", "earthmobsmod:zombie_flesh", "conjurer_illager:throwing_card", "conjurer_illager:bouncy_ball", "tofucraft:fukumame", "tofucraft:nether_fukumame", "tofucraft:soul_fukumame"]
#Whitelist the projectile mob enchant for mob. Use the full name(eg: minecraft:zombie.
whitelistShootEntity = ["minecraft:skeleton", "minecraft:pillager", "minecraft:shulker", "minecraft:llama", "conjurer_illager:conjurer", "earthmobsmod:bone_spider", "earthmobsmod:lobber_zombie", "earthmobsmod:lobber_drowned", "earthmobsmod:melon_golem", "minecraft:piglin", "minecraft:snow_golem", "minecraft:player"]
#Set the MobEnchant on the EnderDragon. If you want more harder fight. should set it! eg: enchantwithmob:thorn.
"Buffed Dragon" = []
#Enable the the spawning of enchanted animal mobs. [true / false]
"Enchanted Animal can Spawn Natural" = false
#Enable enchanting yourself. [true / false]
"Enchant yourself" = true
#Enable Change Size When Enchanted. [true / false]
"Change Size" = false
#Enable Increase Health like Dungeons When Enchanted. [true / false]
"Increase Health like Dungeons" = false
#Enable Player More Bigger When You have Huge Enchant. [true / false]
"Big Your Self" = false
#Enable All MobEnchant for all mob. [true / false]
UniversalEnchant = false
#Set The Difficulty Base Enchanted Mob Spawn Percent. [(Difficulty Base Percent * Difficulty id) + (Effective Difficulty Percent * Effective Difficulty)]
#Range: 0.0 ~ 1.0
"Difficulty Enchanted Spawn Percent" = 0.005
#Set The Effective Difficulty Base Enchanted Mob Spawn Percent [(Difficulty Base Percent * Difficulty id) + (Effective Difficulty Percent * Effective Difficulty)]
#Range: 0.0 ~ 1.0
"Effective Difficulty Enchanted Spawn Percent" = 0.025

