
[types]

	[types.wood_type]

		[types.wood_type.quark]
			bamboo = true
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.deeperdarker]
			echo = true

		[types.wood_type.ulterlands]
			cedar = true

		[types.wood_type.ad_astra]
			aeronos = true
			strophar = true
			glacian = true

		[types.wood_type.aether]
			skyroot = true

		[types.wood_type.aether_redux]
			fieldsprout = true
			blightwillow = true
			cloudcap = true
			springshroom = true
			crystal = true
			glacia = true

		[types.wood_type.createdieselgenerators]
			chip_wood = true

	[types.leaves_type]

		[types.leaves_type.deeperdarker]
			echo = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			pink_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.ulterlands]
			souldrained = true
			cedar = true
			frax = true

		[types.leaves_type.ad_astra]
			glacian = true

		[types.leaves_type.fruitsdelight]
			pear = true
			hawberry = true
			lychee = true
			mango = true
			persimmon = true
			peach = true
			orange = true
			apple = true
			mangosteen = true
			bayberry = true
			kiwi = true
			fig = true
			durian = true

		[types.leaves_type.aether]
			skyroot = true
			golden_oak = true
			crystal = true
			crystal_fruit = true
			holiday = true
			decorated_holiday = true

		[types.leaves_type.aether_redux]
			blightwillow = true
			glacia = true
			gilded_oak = true
			blighted_skyroot = true

[entries]

	[entries.wood_type]

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			hollow_log = true
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true

		[entries.wood_type.dramaticdoors]
			short_door = true
			tall_door = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

