StartupEvents.registry("fluid", e =>{
    e.create("createdimensionalrelics:benzene")
    e.create("createdimensionalrelics:methane")
    e.create("createdimensionalrelics:nitrogen")
    e.create("createdimensionalrelics:ammonia")
    e.create("createdimensionalrelics:carbon_dioxide")
    e.create("createdimensionalrelics:sodium_hydroxide_fluid")
    e.create("createdimensionalrelics:sodium_hypochlorite_fluid")
    e.create("createdimensionalrelics:hypochlorous_acid")
    e.create("createdimensionalrelics:hypertonic_saline")
    e.create("createdimensionalrelics:hydrazine")
    e.create("createdimensionalrelics:UDMH")
})