BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("tier_1_rocket")
    .pattern("a   a", "b   b", "b   b", "     ", "     ", "     ", "     ", "     ", "     ")
    .pattern(" aaa ", " bbb ", " bbb ", " cdc ", " cfc ", " cdc ", " cdc ", "  d  ", "     ")
    .pattern(" aaa ", " ebb ", " bbb ", " d d ", " f f ", " d d ", " d d ", " d d ", "  d  ")
    .pattern(" aaa ", " bbb ", " bbb ", " cdc ", " cfc ", " cdc ", " cdc ", "  d  ", "     ")
    .pattern("a   a", "b   b", "b   b", "     ", "     ", "     ", "     ", "     ", "     ")
    .center("e", 'createdimensionalrelics:rocket_core_tier_1')
    .where(" ", Blocks.AIR)
    .where("a", 'createdimensionalrelics:steel_engine')
    .where("b", 'createdimensionalrelics:steel_tank')
    .where("c", 'ad_astra:steel_pillar')
    .where("d", 'ad_astra:steel_plating')
    .where("f", 'mekanism:structural_glass')
    .craftingItem("create:wrench")
    .resultItem("ad_astra:tier_1_rocket")
    .resultAction((level, pos, player) => {
        player.swing()
    })
    .build())
