ServerEvents.recipes(e => {
    BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("tier_1_rocket")
        .pattern("a   a", "b   b", "b   b", "     ", "     ", "     ", "     ", "     ", "     ")
        .pattern(" aaa ", " bbb ", " bbb ", " cdc ", " cfc ", " cdc ", " cdc ", "  d  ", "     ")
        .pattern(" aaa ", " ebb ", " bbb ", " d d ", " f f ", " d d ", " d d ", " d d ", "  d  ")
        .pattern(" aaa ", " bbb ", " bbb ", " cdc ", " cfc ", " cdc ", " cdc ", "  d  ", "     ")
        .pattern("a   a", "b   b", "b   b", "     ", "     ", "     ", "     ", "     ", "     ")
        .center("e", "createdimensionalrelics:rocket_core_tier_1")
        .whereCond(" ", () => true)
        .where("a", "createdimensionalrelics:steel_engine")
        .where("b", "createdimensionalrelics:steel_tank")
        .where("c", "ad_astra:steel_pillar")
        .where("d", "ad_astra:steel_plating")
        .where("f", "mekanism:structural_glass")
        .craftingItem("create:wrench")
        .resultEntity("ad_astra:tier_1_rocket")
        .resultAction((level, pos, player) => {
            player.swing()
        })
        .build())

    BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("tier_2_rocket")
        .pattern("a   a", "b   b", "b   b", "     ", "     ", "     ", "     ", "     ", "     ")
        .pattern(" aaa ", " bbb ", " bbb ", " cdc ", " cfc ", " cdc ", " cdc ", "  d  ", "     ")
        .pattern(" aaa ", " ebb ", " bbb ", " d d ", " f f ", " d d ", " d d ", " d d ", "  d  ")
        .pattern(" aaa ", " bbb ", " bbb ", " cdc ", " cfc ", " cdc ", " cdc ", "  d  ", "     ")
        .pattern("a   a", "b   b", "b   b", "     ", "     ", "     ", "     ", "     ", "     ")
        .center("e", "createdimensionalrelics:rocket_core_tier_2")
        .whereCond(" ", () => true)
        .where("a", "createdimensionalrelics:desh_engine")
        .where("b", "createdimensionalrelics:desh_tank")
        .where("c", "ad_astra:desh_pillar")
        .where("d", "ad_astra:desh_plating")
        .where("f", "mekanism:structural_glass")
        .craftingItem("create:wrench")
        .resultEntity("ad_astra:tier_2_rocket")
        .resultAction((level, pos, player) => {
            player.swing()
        })
        .build())

    BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("tier_3_rocket")
        .pattern("a a a", "b b b", "b b b", "  b  ", "     ", "     ", "     ", "     ", "     ", "     ")
        .pattern(" aaa ", " bbb ", " bbb ", " cdc ", " cfc ", " cdc ", " cdc ", "  d  ", "  d  ", "     ")
        .pattern(" aaa ", " ebb ", " bbb ", " d d ", " f f ", " d d ", " d d ", " d d ", " d d ", "  d  ")
        .pattern(" aaa ", " bbb ", " bbb ", " cdc ", " cfc ", " cdc ", " cdc ", "  d  ", "  d  ", "     ")
        .pattern("a a a", "b b b", "b b b", "  b  ", "     ", "     ", "     ", "     ", "     ", "     ")
        .center("e", "createdimensionalrelics:rocket_core_tier_3")
        .whereCond(" ", () => true)
        .where("a", "createdimensionalrelics:ostrum_engine")
        .where("b", "createdimensionalrelics:ostrum_tank")
        .where("c", "ad_astra:ostrum_pillar")
        .where("d", "ad_astra:ostrum_plating")
        .where("f", "mekanism:structural_glass")
        .craftingItem("create:wrench")
        .resultEntity("ad_astra:tier_3_rocket")
        .resultAction((level, pos, player) => {
            player.swing()
        })
        .build())

    BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("tier_4_rocket")
        .pattern(" a ", " b ", " b ", " b ", " b ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ")
        .pattern(" c ", " c ", " c ", " c ", " c ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ")
        .pattern("aaa", "bbb", "bbb", "bbb", "cdc", "cfc", "cdc", "cdc", "cdc", " d ", " d ", "   ", "   ")
        .pattern("aaa", "ebb", "bbb", "bbb", "d d", "f f", "d d", "d d", "d d", "d d", "d d", " d ", " d ")
        .pattern("aaa", "bbb", "bbb", "bbb", "cdc", "cfc", "cdc", "cdc", "cdc", " d ", " d ", "   ", "   ")
        .pattern(" c ", " c ", " c ", " c ", " c ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ")
        .pattern(" a ", " b ", " b ", " b ", " b ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ")
        .center("e", "createdimensionalrelics:rocket_core_tier_4")
        .whereCond(" ", () => true)
        .where("a", "createdimensionalrelics:calorite_engine")
        .where("b", "createdimensionalrelics:calorite_tank")
        .where("c", "ad_astra:calorite_pillar")
        .where("d", "ad_astra:calorite_plating")
        .where("f", "mekanism:structural_glass")
        .craftingItem("create:wrench")
        .resultEntity("ad_astra:tier_4_rocket")
        .resultAction((level, pos, player) => {
            player.swing()
        })
        .build())
})
