BlockCrafting.addMultiblockStructure(MultiblockStructureBuilder.create("tier_1_rocket")
    .pattern("a   a", "a   a", "     ", "     ", "     ", "     ", "     ", "     ", "     ")
    .pattern(" aaa ", " aaa ", " aaa ", " aaa ", " aaa ", " aca ", "  a  ", "     ", "     ")
    .pattern(" aaa ", " aaa ", " aba ", " aba ", " a a ", " a a ", " a a ", "  a  ", "  d  ")
    .pattern(" aaa ", " aaa ", " aea ", " aaa ", " aaa ", " aaa ", "  a  ", "     ", "     ")
    .pattern("a   a", "a   a", "     ", "     ", "     ", "     ", "     ", "     ", "     ")
    .center("e", Blocks.STONE)
    .where(" ", Blocks.AIR)
    .where("a", "alloyed:steel_casing")
    .where("b", "alloyed:steel_scaffolding")
    .where("c", "create_crystal_clear:andesite_clear_glass_casing")
    .where("d", "minecraft:lightning_rod")
    .craftingItem("create:wrench")
    .resultItem("ad_astra:tier_1_rocket")
    .resultAction((level, pos, player) => {
        player.swing()
    })
    .build())
